# Generated by Django 2.1.2 on 2018-12-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=150)),
                ('costoPresupuestado', models.IntegerField()),
                ('costoReal', models.IntegerField()),
                ('tienda', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('PcFactoria', 'PcFactoria'), ('ABCFunciona', 'ABCFunciona'), ('Me109cito', 'Me109cito')], default='Seleccionar', max_length=50, verbose_name='Tienda')),
                ('notaAdicional', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTienda', models.CharField(max_length=150)),
                ('nombreSucursal', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
    ]
